---
- name: Create multiple local users
  hosts: webservers
  vars_files:
    - users_vars.yml
  tasks:
    - name: Add webadmin group
      group:
        name: webadmin
        state: present

    - name: Create user accounts
      user:
        name: "{{ item.username }}"
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_my_rsa
        groups: webadmin
        append: yes
      loop: "{{ users }}"

