collections:
    - name: infra.controller_configuration
    - name: ansible.controller
 
---
- name: Playbook to configure ansible controller post installation
  hosts: all
  vars:
    controller_configuration_settings_secure_logging: true
    controller_hostname: ***
    controller_oauthtoken: ***
  collections:
    - infra.controller_configuration
    - ansible.controller
  pre_tasks:
    - name: Include vars from controller_configs directory
      ansible.builtin.include_vars:
        dir: ./vars
        extensions: ["yml"]
  roles:
    - {role: infra.controller_configuration.settings, when: controller_settings is defined}
 
---
controller_settings:
  settings:
    AUTH_LDAP_SERVER_URI: ldaps://{{ ldap_domain }}:636
    AUTH_LDAP_BIND_DN: CN={{ ldap_username }},CN=Users,DC={{ ldap_domain }},DC=com
    AUTH_LDAP_BIND_PASSWORD: "{{ ldap_password }}"
    AUTH_LDAP_USER_DN_TEMPLATE: "uid=%(user)s,ou=Users,dc=example,dc=com"
    AUTH_LDAP_GROUP_TYPE: "MemberDNGroupType"
    AUTH_LDAP_REQUIRE_GROUP: ""
    AUTH_LDAP_DENY_GROUP: ""
    AUTH_LDAP_START_TLS: "Off"
    AUTH_LDAP_USER_SEARCH: ["CN=Users,DC=example,DC=com","SCOPE_SUBTREE","(sAMAccountName=%(user)s)"]
    AUTH_LDAP_GROUP_SEARCH: ["CN=Users,DC=example,DC=com","SCOPE_SUBTREE","(objectClass=group)"]
    AUTH_LDAP_USER_ATTR_MAP: {"first_name":"givenName","last_name":"sn","email":"mail"}
    AUTH_LDAP_GROUP_TYPE_PARAMS: {"member_attr":"member","name_attr":"cn"}
    AUTH_LDAP_USER_FLAGS_BY_GROUP: {"is_superuser":["CN=SuperUsers,CN=Users,DC=example,DC=com","CN=TowerADM,CN=Users,DC=example,DC=com"]}
 
