---
- name: Allow Developer Access To Dev Servers
  hosts: localhost
  gather_facts: no
  vars_files: var-file.yml
  tasks:
    - name: Set up multiple authorized keys
      blockinfile:
        path: /tmp/output.txt
        create: yes
        marker: "<user>"
        block: |
          key = "{{ lookup('file', item) }}"
      loop: "{{ public_key_lists | map(attribute='public_keys')|flatten }}"
