---
- name: Add Users To IDM
  hosts: localhost
  gather_facts: no
  vars_files: vars-file.yml
  tasks:
    - name: Create Users
      blockinfile:
        path: /tmp/outputfile.txt
        marker: "< USER  {{item.key }}>"
        create: yes
        block: |
          name: "{{ item.key }}"
          givenname: "{{ item.value.firstname }}"
          sn: "{{ item.value.surname }}"
          displayname: "{{ item.value.firstname + ' ' + item.value.surname }}"
          sshpubkey: "{{ lookup('file', item.value.pub_key_file) }}"
      loop: "{{ users | dict2items }}"
