---
# tasks file for roles/inventory
- name: Add app servers in webservers host group
  add_host:
     group: webservers
     name: "{{ item }}"
     ansible_ssh_private_key_file: /home/devops/.ssh/id_rsa
     ansible_ssh_user: devops
  loop:
    - "app1.{{GUID}}.internal"
    - "app2.{{GUID}}.internal"
- name: Add appdb servers in db host group
  add_host:
     group: db
     name: "{{ item }}"
     ansible_ssh_private_key_file: /home/devops/.ssh/id_rsa
     ansible_ssh_user: devops
  loop:
    - "appdb1.{{GUID}}.internal"
- name: Add frontend servers in lb host group
  add_host:
     group: lb
     name: "{{ item }}"
     ansible_ssh_private_key_file: /home/devops/.ssh/id_rsa
     ansible_ssh_user: devops
  loop:
    - "frontend1.{{GUID}}.internal"
- name: Add frontend servers in lb host group
  add_host:
     group: samba_servers
     name: "{{ item }}"
     ansible_ssh_private_key_file: /home/devops/.ssh/id_rsa
     ansible_ssh_user: devops
  loop:
    - "support1.{{GUID}}.internal"
- name: Add frontend servers in lb host group
  add_host:
     group: mailserver
     name: "{{ item }}"
     ansible_ssh_private_key_file: /home/devops/.ssh/id_rsa
     ansible_ssh_user: devops
  loop:
    - "support1.{{GUID}}.internal"
- name: Add app servers in webservers host group
  add_host:
     group: everyone
     name: "{{ item }}"
     ansible_ssh_private_key_file: /home/devops/.ssh/id_rsa
     ansible_ssh_user: devops
  loop:
    - "app1.{{GUID}}.internal"
    - "app2.{{GUID}}.internal"
    - "frontend1.{{GUID}}.internal"
    - "appdb1.{{GUID}}.internal"
