- name: create a user and add it to sudoers file
  hosts: all
  gather_facts: false
  become: true
  vars_files: vars.yaml
  tasks:
    - name: create {{ username }} user
      user: 
        name: "{{ username }}"
        password: "{{ userpass | password_hash('sha512') }}"
        update_password: on_create
        generate_ssh_key: yes
        ssh_key_file: .ssh/id_rsa

    - name: add {{ username }} to sudoers
      copy:
        content: "{{ username }} ALL = (root) NOPASSWD:ALL \n"
        dest: /etc/sudoers.d/{{ username }}
        mode: '0440'

    - name: Set authorized key taken from file
      authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ lookup('file', '/home/{{ username }}/.ssh/id_rsa.pub') }}"
