---
- name: Tests
  hosts: ipaserver
  become: true
  gather_facts: false

  tasks:
  # Ensure host server is present in Sudo Rule
  - ipasudorule:
      ipaadmin_password: SomeADMINpassword
      name: testrule1
      host: server
      action: member
