---
- name: Tests
  hosts: ipaserver
  become: true

  tasks:
  # Ensure sudorule command is disabled
  - ipasudorule:
      ipaadmin_password: SomeADMINpassword
      name: testrule1
      state: disabled
