- name: "Create a new VM at VMWARE"
  hosts: localhost
  gather_facts: false
  connection: local
  
  tasks:
    - include_vars: vars.yml
    - include_tasks: set-cluster-info.yml
    - include_tasks: create-vm-task.yml
      loop: "{{ ocpnodes_vms.vm_name }}"
