variables:
  LAUNCH_TOWER_JOB: awx -k job_template launch 
  TOWER_CREDENTIALS:  --conf.host https://towersingle.aydin.lab --conf.username admin --conf.password wuFSMsWemRirj9 
  GIT_REPO: ssh://git@gitlab.consulting.redhat.com:2222/maydin/ansibletower_basics.git

stages:
  - lint
  - deploy
  - auto_merge

# First stage; all branches
syntax check and linting:
  stage: lint
  script:
    - if ls *.yml; then true; else echo "No playbooks found!"; exit 1; fi
    - ansible-lint *.yml

#Second stage; only dev branch
launch test job:
  stage: deploy
  script:
    - $LAUNCH_TOWER_JOB basicpipelinetest_dev $TOWER_CREDENTIALS
    - echo $?
  only:
    - dev

#Second stage; only the master branch
launch prod job:
  stage: deploy
  script:
    - $LAUNCH_TOWER_JOB basicpipelinetest_prod $TOWER_CREDENTIALS
    - echo $?
  only:
    - master

#Third stage; only applies to the dev branch
push to master:
  stage: auto_merge
  script:
    - git remote set-url origin $GIT_REPO
    - git checkout dev && git pull
    - git checkout master && git pull
    - git merge --no-ff dev
    - git push origin master
  only:
    - dev
