- name: disable all repos except one
  hosts: all
  gather_facts: false
  tasks:
    - name: Get the list of repositories
      rhsm_repository:
        name: '*'
      register: rhsm_repository
    - name: Disable all repositories except rhel-7-server-rpms
      rhsm_repository:
        name: "{{ item }}"
        state: disabled
      with_items: "{{
        rhsm_repository.repositories |
        map(attribute='id') |
        difference(['rhel-7-server-rpms','rhel-7-server-extras-rpms','rhel-7-server-satellite-tools-6.2-rpms']) }}"
