- hosts: localhost
  connection: local
  tasks:
  - name: serial_play playbook
    stat:
      path: /home/devops/ansible_implementation/serial_play.yml
    register: dict_facts
  - fail:
      msg: "FAILED: playbook is not present"
    when: dict_facts.stat.exists != true
  - debug:
      msg: "Success: playbook pressent" 
    when: dict_facts.stat.exists == true
