- hosts: localhost
  tasks:
  - include_role:
      name: inventory

- hosts: db
  become: yes
  tasks:
  - name: Delete my.cnf
    file:
      path: /etc/my.cnf
      state: absent
  - name: Remove mariadb
    yum:
      name: "{{ item }}"
      state: absent
    loop:
     - mariadb-server
     - MySQL-python
     - mariadb-libs
