- hosts: localhost
  gather_facts: false
  tasks:
  - name: Check URL
    shell: curl -k https://app1.{{GUID}}.internal
    register: output
  - debug: var=output.stdout
  - fail:
      msg: "FAILED: Secure webserver is not configured"
    when: "'This is a test page.' not in output.stdout"
  - debug:
      msg: "Success: Secure webserver is configured" 
    when: "'This is a test page.' in output.stdout"
